### ISSUE TITLE
We didn't opt-in but got an issue by chainalert-bot in our repo

### ISSUE THREAD

**Issue by Jolg42** [Checkmarx/chainalert-github-action#7]
Hi there,

Here is a "suspicious" issue
https://github.com/prisma/language-tools/issues/1014

It comes from the bot 
https://github.com/chainalert-bot

It was opened and closed, we didn't opt-in to this.

Could you explain how it happened maybe?

**Comment by kaplanlior** [comment]
Hi @Jolg42 ,

First  - thanks for reaching out. I appreciate the question & feedback.

ChainAlert monitors all new releases to NPM, checking for suspicious findings.

We noticed quite a few prisma/language-tools releases today to NPM, over a short time period, and that caused a confusion.

We'll be happy to see you opt-in to get alerts for the packages prisma depends on (although I noticed you mainly have devDependencies).

**Comment by Jolg42** [comment]
Oh ok! So we run a publishing of some package for each `dev` Prisma version, which are triggered for ~every commit on main branch.

It could be interesting to opt-in maybe, though I didn't check in details about what the tool does/provides at the moment.

**Comment by kaplanlior** [comment]
My personal guess is that there isn't a need to publish each commit to NPM and beta/RC would be suffice for others to test changes. But that's your decision.

You're welcome to visit our main page for details about what we do. Feel free to ping me for questions.

**Comment by Jolg42** [comment]
Sure, things could be done differently.
Right now the main branch there is publishing to a `dev` tag and once every 2 weeks when we do a release it goes to `latest`.

**Comment by millsp** [comment]
How do we opt-out to stop the issues from being created?

**Comment by markov00** [comment]
@kaplanlior is there a way to `opt-out`?

**Comment by kaplanlior** [comment]
Our aim is to verify the code published on NPM is well known and verified.
For certain behaviors we double check regarding no "foul play" (e.g. by core developers acknowledge)

We can opt you out if you wish to forgo this kind of security related checks.

Further details were discussed in elastic/elastic-charts#1615
